"""Render docs/risk-model-card.md from a model's metadata.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def pct(value: float) -> str:
    return f"{value * 100:.2f}%"


def render(meta: dict[str, Any]) -> str:
    m = meta["metrics"]
    th = meta["thresholds"]
    cost = meta["cost_model"]
    data = meta["data"]
    rows = [
        "# Risk model card",
        "",
        f"**Model:** `{meta['version']}` — {meta['algorithm']}. Trained {meta['trained_at'][:10]} "
        f"in {meta['training_seconds']} s. Generated by `uv run python -m ml.model_card`.",
        "",
        "## Intended use",
        "",
        "Scores payments in the Tally *simulation* before authorization. The score is combined "
        "with versioned rules; the model can allow, send to review or step-up, or block. It is "
        "not validated on real payment data and must not be used for real decisions.",
        "",
        "## Data",
        "",
        f"- Synthetic events from `{data['generator']}` (seed {data['seed']}, {data['days']} days, "
        f"{data['customers']:,} customers): legitimate spending with look-alike behaviour "
        "(micro-payment bursts, one-off large payments to new payees, travel, device changes) "
        "and three fraud patterns (card testing, account takeover including on the victim's own "
        "device, mule fan-in). Labels include noise: 3% of fraud unreported and 0.05% friendly "
        "fraud.",
        f"- Split by time — {data['split']} — so validation and test are strictly after "
        f"training. Rows: train {m['train_rows']:,}, validation {m['validation_rows']:,}, "
        f"test {m['test_rows']:,}; test fraud rate {pct(m['fraud_rate_test'])}.",
        "- Features (19) are computed by `services/risk/features.py`, the same code the service "
        "uses online; `tests/integration/test_risk_feature_parity.py` checks identical vectors "
        "from Redis and offline replay.",
        "",
        "## Performance (held-out test window)",
        "",
        "| Metric | Value |",
        "| --- | ---: |",
        f"| PR-AUC (average precision) | {m['pr_auc']:.4f} |",
        f"| ROC-AUC | {m['roc_auc']:.4f} |",
        f"| Recall / precision at 0.1% FPR | {pct(m['recall_at_fpr_0.001'])} / "
        f"{pct(m['precision_at_fpr_0.001'])} |",
        f"| Recall / precision at 1% FPR | {pct(m['recall_at_fpr_0.01'])} / "
        f"{pct(m['precision_at_fpr_0.01'])} |",
        f"| Brier score (calibrated) | {m['brier_calibrated']:.5f} |",
        f"| Expected calibration error | {m['ece_calibrated']:.5f} |",
        f"| ONNX vs LightGBM max score difference | {m['onnx_max_abs_diff']:.1e} |",
        "",
        "### Operating thresholds (chosen on validation by cost)",
        "",
        f"Missed fraud costs its amount; a review costs ₹{cost['review_cost_rupees']}; a wrongly "
        f"blocked payment costs ₹{cost['block_false_positive_cost_rupees']}. The review threshold "
        f"({th['review']:.4f}) minimises validation cost; the block threshold ({th['block']:.4f}) "
        f"is the lowest at or above it with validation precision ≥ "
        f"{pct(cost['block_min_precision'])}.",
        "",
        "| At threshold | Recall | Precision |",
        "| --- | ---: | ---: |",
        f"| Review / step-up | {pct(m['recall_at_review_threshold'])} | "
        f"{pct(m['precision_at_review_threshold'])} |",
        f"| Block | {pct(m['recall_at_block_threshold'])} | "
        f"{pct(m['precision_at_block_threshold'])} |",
        "",
        f"False-positive rate at the review threshold: {pct(m['false_positive_rate_review'])}. "
        f"Test-window cost: ₹{m['cost_rupees_model']:,.0f} with the model vs "
        f"₹{m['cost_rupees_no_model']:,.0f} of fraud with no screening.",
        "",
        "Recall by fraud pattern at the review threshold: "
        + ", ".join(f"{k} {pct(v)}" for k, v in m["recall_by_pattern_at_review"].items())
        + ".",
        "",
        f"Rules only (default rule set, no model): recall {pct(m['rules_only']['recall'])}, "
        f"precision {pct(m['rules_only']['precision'])}, false-positive rate "
        f"{pct(m['rules_only']['false_positive_rate'])}.",
        "",
        "## Explainability",
        "",
        "Every decision stores its top three positive TreeSHAP contributions (LightGBM "
        "`pred_contrib`, exact for trees) mapped to reason codes such as `DEVICE_MANY_CARDS`, "
        "`NEW_DEVICE` or `AMOUNT_VS_HISTORY`, alongside the rule reasons.",
        "",
        "## Fairness and subgroup notes",
        "",
        f"Legitimate customers whose IP country differs from their account country (travellers, "
        f"non-resident Indians; {m['legit_geo_mismatch_rows']:,} test rows) are flagged at "
        f"{pct(m['fpr_legit_geo_mismatch'])} versus {pct(m['fpr_legit_home'])} for customers at "
        "home. This is a material disparity: `geo_mismatch` is predictive in the synthetic data "
        "but correlates with nationality and residence. Mitigations before any real use: step-up "
        "instead of block for this segment, monitor the per-segment false-positive rate, and "
        "consider removing or constraining the feature. No protected attributes are used "
        "directly; the synthetic data cannot measure outcomes by gender, religion, caste or age.",
        "",
        "## Monitoring and lifecycle",
        "",
        "- Drift: PSI and KS per feature and on the score against the training baselines stored "
        "in `metadata.json` (`POST /v1/drift/run`); PSI ≥ 0.2 is an alert.",
        "- Feedback: chargebacks and analyst review outcomes become `risk_labels` joined to the "
        "logged feature vectors; `ml/retrain.py` retrains, registers the candidate and makes it "
        "the shadow challenger only if it passes the evaluation gate (PR-AUC and recall at 1% "
        "FPR within 0.02 of the champion, ONNX parity). Champion promotion needs maker-checker.",
        "- Serving: ONNX Runtime score + LightGBM TreeSHAP; in-process decision latency measured "
        "in `tests/integration/test_risk_flow.py` (see PROGRESS for the latest numbers).",
        "",
        "## Limits",
        "",
        "- The generator and model were built together; real fraud is adaptive and far less "
        "separable. Treat these metrics as a test of the pipeline, not of fraud performance.",
        "- Calibration is isotonic on one validation window; it will drift with base rates.",
    ]
    return "\n".join(rows) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default="ml/artifacts/fraud-gbm-v1")
    parser.add_argument("--output", default="docs/risk-model-card.md")
    args = parser.parse_args()
    meta = json.loads((Path(args.model) / "metadata.json").read_text())
    Path(args.output).write_text(render(meta), encoding="utf-8")


if __name__ == "__main__":
    main()
