apiVersion: v1
kind: ConfigMap
metadata:
  name: tally-config
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "tally.labels" (dict "root" $ "name" "") | nindent 4 }}
data:
  TALLY_ENVIRONMENT: {{ .Values.global.environment | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.global.otlpEndpoint | quote }}
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
