#!/usr/bin/env bash
# Local Kubernetes drill for the Helm chart and Argo Rollouts canary (Phase 14).
#
#   scripts/k8s_local.sh up      minikube profile "tally" (Calico, so NetworkPolicies are
#                                enforced), Argo Rollouts, in-cluster Postgres/Redis/Prometheus,
#                                images, and the chart with freshly generated secrets
#   scripts/k8s_local.sh drill   steady merchant traffic, then (1) a healthy core release that
#                                must be promoted and (2) a broken one that analysis must abort
#   scripts/k8s_local.sh down    delete the "tally" profile
#
# Uses its own minikube profile and kube context ("tally"); other clusters are never touched.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STATE="$ROOT/.data/k8s-local"
BIN="$ROOT/.data/bin"
PROFILE=tally
NS=tally-local
ROLLOUTS_VERSION=v1.8.3
HELM_VERSION=v3.19.0
mkdir -p "$STATE" "$BIN"

k() { kubectl --context "$PROFILE" "$@"; }
log() { printf '[%s] %s\n' "$(date +%H:%M:%S)" "$*"; }

helm_bin() {
  if [[ ! -x "$BIN/helm" ]]; then
    local os arch
    os="$(uname -s | tr '[:upper:]' '[:lower:]')"
    arch="$(uname -m)"; [[ $arch == x86_64 ]] && arch=amd64; [[ $arch == aarch64 ]] && arch=arm64
    curl -fsSL "https://get.helm.sh/helm-$HELM_VERSION-$os-$arch.tar.gz" | tar -xz -C "$STATE"
    mv "$STATE/$os-$arch/helm" "$BIN/helm"
  fi
  echo "$BIN/helm"
}

rand() { python3 -c "import base64,os;print(base64.urlsafe_b64encode(os.urandom(32)).decode())"; }
hex() { python3 -c "import secrets;print(secrets.token_hex(24))"; }

write_secrets() {
  [[ -s "$STATE/secrets.yaml" ]] && return
  local pg ledger_key
  pg="$(hex)"; ledger_key="$(hex)"
  local db="postgresql://tally:$pg@postgres.tally-deps.svc:5432"
  umask 077
  cat >"$STATE/secrets.yaml" <<EOF
# Generated by scripts/k8s_local.sh for a throwaway cluster. Never commit.
secrets:
  inlineValues:
    POSTGRES_PASSWORD: "$pg"
    TALLY_DATABASE_URL: "$db/tally"
    LEDGER_DATABASE_URL: "$db/tally_ledger"
    VAULT_DATABASE_URL: "$db/tally_vault"
    REDIS_URL: "redis://redis.tally-deps.svc:6379/0"
    TALLY_INTERNAL_KEY: "$(hex)"
    TALLY_RECOVERY_KEY: "$(hex)"
    TALLY_LEDGER_INTERNAL_KEY: "$ledger_key"
    LEDGER_PROVISIONING_KEY: "$ledger_key"
    TALLY_API_KEY_ENCRYPTION_KEY: "$(rand)"
    TALLY_BACKOFFICE_SECRET_KEY: "$(rand)"
    TALLY_STEP_UP_SECRET: "$(hex)"
    TALLY_NETWORK_SIMULATOR_KEY: "$(hex)"
    TALLY_SIMULATOR_ADMIN_KEY: "$(hex)"
    TALLY_KAFKA_USERNAME: "unused-locally"
    TALLY_KAFKA_PASSWORD: "unused-locally"
    TALLY_VAULT_KEK_B64: "$(rand)"
    TALLY_VAULT_TOKENIZE_KEY: "$(hex)"
    TALLY_VAULT_NETWORK_KEY: "$(hex)"
    TALLY_VAULT_PUBLISHABLE_KEYS: "pk_test_tally_local"
    TALLY_DEMO_KEY_ID: "unused"
    TALLY_DEMO_SECRET_B64: "unused"
    TALLY_RISK_INTERNAL_KEY: "unused"
EOF
}

secret_value() { sed -n "s/^    $1: \"\\(.*\\)\"$/\\1/p" "$STATE/secrets.yaml"; }

image_tag() { cat "$STATE/image-tag" 2>/dev/null || echo drill; }

install_chart() {
  "$(helm_bin)" --kube-context "$PROFILE" upgrade --install tally "$ROOT/infra/helm/tally" \
    --namespace "$NS" -f "$ROOT/infra/helm/tally/ci/local-values.yaml" -f "$STATE/secrets.yaml" \
    --set "global.image.tag=$(image_tag)" --wait --timeout 12m "$@"
}

rollout_field() { k -n "$NS" get rollout tally-core -o "jsonpath=$1"; }

wait_rollout() { # wait_rollout <phase regex> <timeout seconds>
  local deadline=$((SECONDS + $2)) phase
  while ((SECONDS < deadline)); do
    phase="$(rollout_field '{.status.phase}')"
    [[ $phase =~ $1 ]] && { echo "$phase"; return 0; }
    sleep 5
  done
  echo "timeout (phase=$(rollout_field '{.status.phase}'))"
  return 1
}

cmd_up() {
  if ! minikube -p "$PROFILE" status >/dev/null 2>&1; then
    minikube start -p "$PROFILE" --driver=docker --cpus=${K8S_CPUS:-6} --memory=${K8S_MEMORY:-7168} --cni=calico \
      --kubernetes-version=v1.31.4 --wait=all
  fi
  log "Argo Rollouts $ROLLOUTS_VERSION"
  k create namespace argo-rollouts --dry-run=client -o yaml | k apply -f - >/dev/null
  k apply -n argo-rollouts --server-side -f \
    "https://github.com/argoproj/argo-rollouts/releases/download/$ROLLOUTS_VERSION/install.yaml" >/dev/null
  write_secrets
  log "dependencies (Postgres, Redis, Prometheus)"
  k create namespace tally-deps --dry-run=client -o yaml | k apply -f - >/dev/null
  k -n tally-deps create secret generic postgres --from-literal="password=$(secret_value POSTGRES_PASSWORD)" \
    --dry-run=client -o yaml | k apply -f - >/dev/null
  k apply -f "$ROOT/infra/k8s/local/deps.yaml" >/dev/null
  k -n tally-deps rollout status deploy/postgres --timeout=5m
  k -n tally-deps rollout status deploy/redis --timeout=5m
  k -n monitoring rollout status deploy/kube-prometheus-stack-prometheus --timeout=5m
  k -n argo-rollouts rollout status deploy/argo-rollouts --timeout=5m
  log "images"
  # Content-addressed tag: a rebuilt image changes the pod template, so it actually rolls out.
  local tag
  tag="drill-$(docker image inspect -f '{{.Id}}' tally/python:dev | cut -c8-19)"
  docker tag tally/python:dev "tally/python:$tag"
  minikube -p "$PROFILE" image load "tally/python:$tag"
  echo "$tag" >"$STATE/image-tag"
  log "namespace $NS (Pod Security: restricted)"
  k create namespace "$NS" --dry-run=client -o yaml | k apply -f - >/dev/null
  k label namespace "$NS" --overwrite pod-security.kubernetes.io/enforce=restricted \
    pod-security.kubernetes.io/warn=restricted tally.io/environment=local >/dev/null
  log "helm install"
  install_chart
  wait_rollout '^Healthy$' 600
  k -n "$NS" get pods -o wide
}

loadgen() {
  local creds key_id secret_b64
  creds="$(k -n "$NS" exec deploy/tally-core-worker -- python -m scripts.canary_traffic seed)"
  key_id="$(python3 -c 'import json,sys;print(json.loads(sys.argv[1])["key_id"])' "$creds")"
  secret_b64="$(python3 -c 'import json,sys;print(json.loads(sys.argv[1])["secret_b64"])' "$creds")"
  k -n "$NS" delete job drill-traffic --ignore-not-found >/dev/null
  k -n "$NS" create secret generic drill-merchant --from-literal="DRILL_KEY_ID=$key_id" \
    --from-literal="DRILL_SECRET_B64=$secret_b64" --dry-run=client -o yaml | k apply -f - >/dev/null
  k apply -f - >/dev/null <<EOF
# The load generator gets its own narrow policy pair: egress to core, and core ingress from it.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: drill-loadgen, namespace: $NS}
spec:
  podSelector: {matchLabels: {tally.io/role: loadgen}}
  policyTypes: [Ingress, Egress]
  egress:
    - to: [{podSelector: {matchLabels: {app.kubernetes.io/name: tally-core}}}]
      ports: [{protocol: TCP, port: 8000}]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: drill-core-from-loadgen, namespace: $NS}
spec:
  podSelector: {matchLabels: {app.kubernetes.io/name: tally-core}}
  policyTypes: [Ingress]
  ingress:
    - from: [{podSelector: {matchLabels: {tally.io/role: loadgen}}}]
      ports: [{protocol: TCP, port: 8000}]
---
apiVersion: batch/v1
kind: Job
metadata: {name: drill-traffic, namespace: $NS}
spec:
  backoffLimit: 0
  template:
    metadata: {labels: {tally.io/role: loadgen}}
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false
      securityContext: {runAsNonRoot: true, runAsUser: 10001, seccompProfile: {type: RuntimeDefault}}
      containers:
        - name: traffic
          image: tally/python:$(image_tag)
          imagePullPolicy: Never
          command: [python, -m, scripts.canary_traffic, traffic, --seconds, "1800", --rate, "0.8"]
          env: [{name: TALLY_CORE_URL, value: "http://tally-core.$NS.svc:8000"}]
          envFrom: [{secretRef: {name: drill-merchant}}]
          resources: {requests: {cpu: 50m, memory: 96Mi}, limits: {memory: 256Mi}}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
EOF
}

prom() { # instant query through the Prometheus pod
  k -n monitoring exec deploy/kube-prometheus-stack-prometheus -- \
    wget -qO- "http://localhost:9090/api/v1/query?query=$(python3 -c 'import sys,urllib.parse;print(urllib.parse.quote(sys.argv[1]))' "$1")"
}

analysis_summary() {
  k -n "$NS" get analysisrun -l rollouts-pod-template-hash="$1" \
    -o jsonpath='{range .items[*]}{range .status.metricResults[*]}{.name}={.phase} ({.count} measurements, failed={.failed}){"\n"}{end}{end}' 2>/dev/null \
    || true
}

cmd_drill() {
  local report="$STATE/drill.md" started took stable_before canary_hash
  log "load generator"
  loadgen
  log "baseline traffic (90 s)"
  sleep 90
  prom 'sum by (status) (rate(tally_http_requests_total{service="core",route=~"/v1/.*"}[1m]))' | head -c 600; echo

  {
    echo "Canary drill $(date -u +%Y-%m-%dT%H:%M:%SZ) on minikube profile $PROFILE (Calico)"
    echo
    echo "| Release | Expected | Result | Time | Analysis |"
    echo "| --- | --- | --- | ---: | --- |"
  } >"$report"

  log "release 1: healthy change (must be promoted)"
  stable_before="$(rollout_field '{.status.stableRS}')"
  started=$SECONDS
  install_chart --set "workloads.core.env.TALLY_RELEASE=good-$(date +%s)" >/dev/null
  canary_hash="$(rollout_field '{.status.currentPodHash}')"
  result="$(wait_rollout '^(Healthy|Degraded)$' 900 || true)"
  took=$((SECONDS - started))
  echo "| healthy config change | promoted | $result (stable $stable_before -> $(rollout_field '{.status.stableRS}')) | ${took} s | $(analysis_summary "$canary_hash" | tr '\n' ' ') |" >>"$report"

  log "release 2: broken ledger URL (must be aborted by analysis)"
  stable_before="$(rollout_field '{.status.stableRS}')"
  started=$SECONDS
  install_chart --set "workloads.core.env.TALLY_RELEASE=bad-$(date +%s)" \
    --set "workloads.core.env.TALLY_LEDGER_URL=http://tally-ledger-missing.$NS.svc:8001" >/dev/null
  canary_hash="$(rollout_field '{.status.currentPodHash}')"
  result="$(wait_rollout '^Degraded$' 900 || true)"
  took=$((SECONDS - started))
  local serving
  serving="$(k -n "$NS" get pods -l "app.kubernetes.io/name=tally-core,rollouts-pod-template-hash=$stable_before" \
    --field-selector=status.phase=Running --no-headers | wc -l | tr -d ' ')"
  echo "| core pointed at a missing ledger | aborted, stable keeps serving | $result: $(rollout_field '{.status.message}'); stable $stable_before still serving with $serving pods | ${took} s | $(analysis_summary "$canary_hash" | tr '\n' ' ') |" >>"$report"

  log "roll forward to the last good spec"
  install_chart >/dev/null
  wait_rollout '^Healthy$' 600 >/dev/null || true
  echo >>"$report"
  echo "Ledger integrity during the drill: min(tally_ledger_integrity_ok) = $(prom 'min(tally_ledger_integrity_ok)' | python3 -c 'import json,sys;r=json.load(sys.stdin)["data"]["result"];print(r[0]["value"][1] if r else "no data")')" >>"$report"
  k -n "$NS" logs job/drill-traffic --tail=1 >>"$report" 2>/dev/null || true
  cat "$report"
}

cmd_down() { minikube delete -p "$PROFILE"; }

case "${1:-}" in
  up) cmd_up ;;
  drill) cmd_drill ;;
  down) cmd_down ;;
  *) echo "usage: $0 up|drill|down" >&2; exit 2 ;;
esac
